import { BrandInfo } from '../types';

export const BRANDS: BrandInfo[] = [
    { name: 'Patagonia', domain: 'patagonia.com' },
    { name: 'The North Face', domain: 'thenorthface.com' },
    { name: 'Arc\'teryx', domain: 'arcteryx.com' },
    { name: 'REI Co-op', domain: 'rei.com' },
    { name: 'Marmot', domain: 'marmot.com' },
    { name: 'Columbia Sportswear', domain: 'columbia.com' },
    { name: 'Osprey', domain: 'osprey.com' },
    { name: 'Black Diamond', domain: 'blackdiamondequipment.com' },
    { name: 'Salomon', domain: 'salomon.com' },
    { name: 'La Sportiva', domain: 'sportiva.com' },
    { name: 'Merrell', domain: 'merrell.com' },
    { name: 'MSR', domain: 'msrgear.com' },
    { name: 'Therm-a-Rest', domain: 'thermarest.com' },
    { name: 'Sea to Summit', domain: 'seatosummit.com' },
    { name: 'Big Agnes', domain: 'bigagnes.com' },
    { name: 'NEMO Equipment', domain: 'nemoequipment.com' },
    { name: 'Deuter', domain: 'deuter.com' },
    { name: 'Gregory', domain: 'gregorypacks.com' },
    { name: 'Smartwool', domain: 'smartwool.com' },
    { name: 'Icebreaker', domain: 'icebreaker.com' },
    { name: 'Outdoor Research', domain: 'outdoorresearch.com' },
    { name: 'Fjällräven', domain: 'fjallraven.com' },
    { name: 'Petzl', domain: 'petzl.com' },
    { name: 'Leki', domain: 'leki.com' },
    { name: 'Sawyer', domain: 'sawyer.com' },
    { name: 'Katadyn', domain: 'katadyn.com' },
    { name: 'Jetboil', domain: 'jetboil.com' },
    { name: 'Snow Peak', domain: 'snowpeak.com' },
    { name: 'Hydro Flask', domain: 'hydroflask.com' },
    { name: 'Yeti', domain: 'yeti.com' },
    { name: 'Stanley', domain: 'stanley1913.com' },
    { name: 'Garmin', domain: 'garmin.com' },
    { name: 'Suunto', domain: 'suunto.com' },
    { name: 'GoPro', domain: 'gopro.com' },
    { name: 'Anker', domain: 'anker.com' },
    { name: 'Goal Zero', domain: 'goalzero.com' },
    { name: 'BioLite', domain: 'bioliteenergy.com' },
    { name: 'Helinox', domain: 'helinox.com' },
    { name: 'GSI Outdoors', domain: 'gsioutdoors.com' },
    { name: 'Platypus', domain: 'platy.com' },
    { name: 'CamelBak', domain: 'camelbak.com' },
    { name: 'Nalgene', domain: 'nalgene.com' },
    { name: 'Buff', domain: 'buff.com' },
    { name: 'Darn Tough', domain: 'darntough.com' },
    { name: 'KEEN', domain: 'keenfootwear.com' },
    { name: 'Hoka One One', domain: 'hoka.com' },
    { name: 'Altra', domain: 'altrarunning.com' },
    { name: 'Vasque', domain: 'vasque.com' },
    { name: 'Lowa', domain: 'lowaboots.com' },
    { name: 'Scarpa', domain: 'scarpa.com' },
    { name: 'Rab', domain: 'rab.equipment' },
    { name: 'Mountain Hardwear', domain: 'mountainhardwear.com' },
    { name: 'PrAna', domain: 'prana.com' },
    { name: 'KÜHL', domain: 'kuhl.com' },
    { name: 'Cotopaxi', domain: 'cotopaxi.com' },
    { name: 'Hyperlite Mountain Gear', domain: 'hyperlitemountaingear.com' },
    { name: 'Zpacks', domain: 'zpacks.com' },
    { name: 'ULA Equipment', domain: 'ula-equipment.com' },
    { name: 'Gossamer Gear', domain: 'gossamergear.com' },
    { name: 'Six Moon Designs', domain: 'sixmoondesigns.com' },
    { name: 'Enlightened Equipment', domain: 'enlightenedequipment.com' },
    { name: 'Feathered Friends', domain: 'featheredfriends.com' },
    { name: 'Western Mountaineering', domain: 'westernmountaingering.com' },
    { name: 'Montbell', domain: 'montbell.us' },
    { name: 'Exped', domain: 'exped.com' },
    { name: 'Mammut', domain: 'mammut.com' },
    { name: 'Eddie Bauer', domain: 'eddiebauer.com' },
    { name: 'LL Bean', domain: 'llbean.com' },
    { name: 'Cabela\'s', domain: 'cabelas.com' },
    { name: 'Bass Pro Shops', domain: 'basspro.com' },
    { name: 'Kelty', domain: 'kelty.com' },
    { name: 'Eureka!', domain: 'eurekatent.com' },
    { name: 'Coleman', domain: 'coleman.com' },
    { name: 'ENO', domain: 'eaglesnestoutfittersinc.com' },
    { name: 'Kammok', domain: 'kammok.com' },
    { name: 'Warbonnet Outdoors', domain: 'warbonnetoutdoors.com' },
    { name: 'Dutchware Gear', domain: 'dutchwaregear.com' },
    { name: 'Toaks', domain: 'toaksoutdoor.com' },
    { name: 'Vargo', domain: 'vargooutdoors.com' },
    { name: 'SOTO', domain: 'sotooutdoors.com' },
    { name: 'Optimus', domain: 'optimusstoves.com' },
    { name: 'Primus', domain: 'primus.us' },
    { name: 'Benchmade', domain: 'benchmade.com' },
    { name: 'Spyderco', domain: 'spyderco.com' },
    { name: 'Leatherman', domain: 'leatherman.com' },
    { name: 'Victorinox', domain: 'victorinox.com' },
    { name: 'Gerber', domain: 'gerbergear.com' },
    { name: 'Fenix', domain: 'fenix-store.com' },
    { name: 'Nitecore', domain: 'nitecore.com' },
    { name: 'Streamlight', domain: 'streamlight.com' },
    { name: 'Thule', domain: 'thule.com' },
    { name: 'Yakima', domain: 'yakima.com' },
    { name: 'Injinji', domain: 'injinji.com' },
    { name: 'Wrightsock', domain: 'wrightsock.com' },
    { name: 'Superfeet', domain: 'superfeet.com' },
    { name: 'Julbo', domain: 'julbo.com' },
    { name: 'Oakley', domain: 'oakley.com' },
    { name: 'Smith Optics', domain: 'smithoptics.com' }
];